name = "fastapi"
compatibility_date="24-05-30"

[vars]
UPSTASH_REDIS_REST_TOKEN = Aa3hAAIncDFhMjdkMjlkZDgxNjI0MGE3ODgxZGQ2OTU5MDAwOTRhOXAxNDQ1MTM

UPSTASH_REDIS_REST_URL = https://stable-skink-44513.upstash.io